# Generated by Django 3.1.2 on 2020-10-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='q2_answer',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='q2_question',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='q1_answer',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
