# Generated by Django 3.1.2 on 2020-10-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201028_1133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='QuizQuestions',
        ),
    ]
