# Generated by Django 3.1.2 on 2020-10-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestions',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q1_question',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q2_question',
            field=models.CharField(max_length=20),
        ),
    ]
