# Generated by Django 3.1.2 on 2020-10-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201028_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='choice_multi',
            new_name='answer_multi',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='choice_text',
            new_name='answer_text',
        ),
    ]
