# Generated by Django 3.1.2 on 2020-10-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20201028_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_multi',
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q1_selected',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q1_answer',
            field=models.IntegerField(default=1),
        ),
    ]
