# Generated by Django 3.1.2 on 2020-10-29 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20201029_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='q2_answer',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='q2_question',
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q1_selected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='quiz',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizname'),
            preserve_default=False,
        ),
    ]
