# Generated by Django 3.1.2 on 2020-10-29 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20201029_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestions',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='name',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q2_answer',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q2_question',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QuizName',
        ),
    ]
