# Generated by Django 3.1.2 on 2020-10-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20201029_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestions',
            name='q2_answer',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='q2_question',
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q1_answer',
            field=models.TextField(default=1),
        ),
    ]
