# Generated by Django 3.1.2 on 2020-10-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quizquestions_q1_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q2_answer',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q2_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q2_question',
            field=models.CharField(default='quest', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q2_selected',
            field=models.IntegerField(default=0),
        ),
    ]
