# Generated by Django 3.1.2 on 2020-10-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20201029_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestions',
            name='q3_answer',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q3_correct',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q3_question',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q3_selected',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q4_answer',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q4_correct',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q4_question',
            field=models.CharField(default='test2', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q4_selected',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q5_answer',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q5_correct',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q5_question',
            field=models.CharField(default='test3', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='q5_selected',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q1_correct',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q1_selected',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q2_correct',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q2_selected',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
