# Generated by Django 3.1.2 on 2020-10-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20201029_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestions',
            options={'verbose_name': 'Quiz Question'},
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q1_correct',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q2_correct',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q3_correct',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q4_correct',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q5_correct',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=0, max_length=1),
        ),
    ]
