# Generated by Django 3.1.2 on 2020-11-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20201030_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestions',
            name='q1_answer',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q1_correct',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q1_question',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q1_selected',
            field=models.CharField(blank=True, editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q2_answer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q2_correct',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q2_selected',
            field=models.CharField(blank=True, editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q3_answer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q3_correct',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q3_selected',
            field=models.CharField(blank=True, editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q4_answer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q4_correct',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q4_selected',
            field=models.CharField(blank=True, editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q5_answer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q5_correct',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='q5_selected',
            field=models.CharField(blank=True, editable=False, max_length=1),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
