# Generated by Django 3.1.2 on 2020-10-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Poll Question'},
        ),
    ]
